name: fatigue_runners_env
channels:
  - defaults
dependencies:
  - ca-certificates=2024.9.24=haa95532_0
  - icu=73.1=h6c2663c_0
  - jpeg=9e=h827c3e9_3
  - krb5=1.20.1=h5b6d351_0
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.0=h70ee33d_0
  - lz4-c=1.9.4=h2bbff1b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py38haa95532_0
  - ply=3.11=py38_0
  - pyqt=5.15.10=py38hd77b12b_0
  - python=3.8.20=h8205438_0
  - qt-main=5.15.2=h19c9488_11
  - setuptools=75.1.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - sqlite=3.45.3=h2bbff1b_0
  - tomli=2.0.1=py38haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wheel=0.44.0=py38haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - cycler==0.12.1
    - et-xmlfile==2.0.0
    - fonttools==4.55.0
    - idna==3.10
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - littleutils==0.2.4
    - matplotlib==3.5.2
    - mplcursors==0.5.2
    - natsort==8.4.0
    - numpy==1.24.3
    - openpyxl==3.0.10
    - outdated==0.2.2
    - packaging==24.2
    - pandas==1.5.3
    - pandas-flavor==0.6.0
    - patsy==1.0.1
    - pillow==10.4.0
    - pingouin==0.5.3
    - pyparsing==3.1.4
    - pyqt5==5.15.0
    - pyqt5-sip==12.15.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - requests==2.32.3
    - scikit-learn==1.3.2
    - scikit-posthocs==0.8.0
    - scipy==1.8.1
    - seaborn==0.13.2
    - six==1.16.0
    - spm1d==0.4.20
    - statsmodels==0.14.0
    - tabulate==0.9.0
    - threadpoolctl==3.5.0
    - tk==0.1.0
    - tzdata==2024.2
    - urllib3==2.2.3
    - xarray==2023.1.0
    - yellowbrick==1.5